# Generated by Django 5.1.6 on 2025-03-21 07:35

from django.db import migrations


def assign_author(apps, schema_editor):
    Task = apps.get_model('todo', 'Task')
    User = apps.get_model('auth', 'User')
    user = User.objects.first()
    if user:
        Task.objects.filter(author__isnull=True).update(author=user)
    # Handle case where no users exist if necessary


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_author'),
    ]

    operations = [
        migrations.RunPython(assign_author)
    ]
